### ISSUE TITLE
Don't show ~/.wine prefix if it's a symlink

### ISSUE THREAD

**Issue by niansa** [winegui/WineGUI#22]
In my case ~/.wine is a symlink to a WineGUI prefix, but it still shows up twice. That should be avoided.

**Comment by melroy89** [comment]
That is a really special edge case. 
I just show the default Wine at the bottom in WineGUI. But I don't know if it's pointing to a WineGUI prefix. The symlink can point to anything.

**Comment by niansa** [comment]
Is something like this possible?

```
if (readlink(this_prefix) == prefix_path.get_parent())
    this_prefix.hide()
```

? That seems like it'd suffice

**Comment by melroy89** [comment]
This has a complexity of `O(n²)`, since this code then need to to check for each prefix if it's matching a symlink of `~/.wine` in a loop. I think you can also just hide the default ~/.wine bottle then.

~~You know. I can also just add a configuration option to show or hide the default wine bottle (~/.wine) to the preferences?~~

Nevermind, I already implemented that. It's called 'Display default Wine prefix bottle". Just go to File->Preferences and then uncheck "Display default Wine prefix bottle". Press 'Save'. Done!

**Comment by niansa** [comment]
Wonderful! Good solution, I like it. Thank you!
